Repository jjochen/JJFloatingActionButton, pull requests merged in 2018-06, with the labels that each got.

#146 Fix circle ci checks
  .circleci/config.yml
Labels: continuous integration

#145 Added functionality to give custom inset for bottom and trailing cons…
  Sources/JJFloatingActionButton+Placement.swift
Labels: added

#147 Release 0.9.2
  CHANGELOG.md
  Example/JJFloatingActionButton/Info.plist
  Example/Podfile.lock
  JJFloatingActionButton.podspec
  docs/Classes.html
  docs/Classes/JJActionItem.html
  docs/Classes/JJAnimationSettings.html
  docs/Classes/JJButtonAnimationConfiguration.html
  docs/Classes/JJButtonAnimationConfiguration/JJButtonAnimationStyle.html
  docs/Classes/JJCircleView.html
  docs/Classes/JJFloatingActionButton.html
  docs/Classes/JJItemAnimationConfiguration.html
  docs/Classes/JJItemLayout.html
  docs/Classes/JJItemPreparation.html
  docs/Enums.html
  docs/Enums/JJActionItemTitlePosition.html
  docs/Enums/JJFloatingActionButtonState.html
  docs/Protocols.html
  docs/Protocols/JJFloatingActionButtonDelegate.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJActionItem.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJAnimationSettings.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJButtonAnimationConfiguration.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJButtonAnimationConfiguration/JJButtonAnimationStyle.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJCircleView.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJFloatingActionButton.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJItemAnimationConfiguration.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJItemLayout.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Classes/JJItemPreparation.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Enums.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Enums/JJActionItemTitlePosition.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Enums/JJFloatingActionButtonState.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Protocols.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/Protocols/JJFloatingActionButtonDelegate.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/index.html
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/Documents/search.json
  docs/docsets/JJFloatingActionButton.docset/Contents/Resources/docSet.dsidx
  docs/docsets/JJFloatingActionButton.tgz
  docs/docsets/JJFloatingActionButton.xml
  docs/index.html
  docs/search.json
Labels: release

#148 Update dependencies and circleci configuration
  .circleci/config.yml
  Example/JJFloatingActionButton.xcodeproj/project.pbxproj
  Example/JJFloatingActionButton.xcodeproj/xcshareddata/xcschemes/JJFloatingActionButton_Example.xcscheme
  Example/JJFloatingActionButton.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/Podfile.lock
  Example/Tests/JJCircleViewSpec.swift
  Example/Tests/ReferenceImages/JJCircleViewSpec/JJCircleView__created_programatically__looks_correct@2x.png
  Example/Tests/ReferenceImages/JJCircleViewSpec/JJCircleView__created_programatically__looks_correct@3x.png
  Example/Tests/ReferenceImages/JJCircleViewSpec/JJCircleView__loaded_from_xib__looks_correct@2x.png
  Example/Tests/ReferenceImages/JJCircleViewSpec/JJCircleView__loaded_from_xib__looks_correct@3x.png
  Example/Tests/ReferenceImages/JJFloatingActionButtonPlacementSpec/JJFloatingActionButton__looks_correct_when_placed_in_view_controller_iPhone11_4_375x812@3x.png
  Gemfile.lock
  README.md
  Rakefile
  Sources/AnimationConfiguration.swift
  Sources/JJFloatingActionButton+Placement.swift
Labels: continuous integration, project config
